### ISSUE TITLE
Caddyfile example please

### ISSUE THREAD

**Issue by bennyzen** [mohammed90/caddy-pocketbase#3]
First off: great idea and thank you so much for this project.

Could you please provide a concrete example `Caddyfile`? Building went smooth, but I'm really struggling getting this to work. 

My Caddyfile looks like this:
```Caddyfile
{
	order pocketbase before file_server
}

{$FQDN} {
	# see https://caddyserver.com/docs/json/apps/pocketbase
	pocketbase {
		listen 8090 # port pocketbase will listen to
		data_dir /pb # default data directory
		origins # all origins allowed when empty
	}
}
```
The problem is,  I'm always getting a random port assigned, as if Caddy is completely ignoring my configuration. Obviously, I'm doing something wrong.

btw: I'm using this in a Docker Compose stack, as this is the way I'm used to deploy services.

**Comment by mohammed90** [comment]
> which in turn makes it unusable.

Why unusable? You can reach it on $FQDN. I agree that there may be an issue. I'll check why you still get the random port, but the port should only be relevant for scenarios where the FQDN is not accessible.

**Comment by bennyzen** [comment]
Thanks for your fast reply.

Look at this:

```bash
https POST localhost/pocketbase/superuser email_address=benny@example.com password=somepassword --verify no

HTTP/1.1 404 Not Found
Alt-Svc: h3=":443"; ma=2592000
Content-Length: 74
Content-Type: application/json
Date: Mon, 17 Mar 2025 16:27:35 GMT
Server: Caddy
Vary: Origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block

{
    "data": {},
    "message": "The requested resource wasn't found.",
    "status": 404
}
```

I'm not able to access any `/pocketbase` route.

In the logs I see the usual PocketBase output with a random port assigned, like this:
```
caddy  | 2025/03/17 13:07:33 Server started at http://127.0.0.1:40033
caddy  | ├─ REST API:  http://127.0.0.1:40033/api/
caddy  | └─ Dashboard: http://127.0.0.1:40033/_/
caddy  | 
caddy  | (!) Launch the URL below in the browser if it hasn't been open already to create your first superuser account:
caddy  | http://127.0.0.1:40033/_/#/pbinstal/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2xsZWN0aW9uSWQiOiJwYmNfMzE0MjYzNTgyMyIsImV4cCI6MTc0MjIxODY1MywiaWQiOiIzc2kyOTdtYnlsNDE3OXYiLCJyZWZyZXNoYWJsZSI6ZmFsc2UsInR5cGUiOiJhdXRoIn0.z7SP9pIwNtPGphZIbNewYz5mudT9JNut3qrv-SaU46g
caddy  | (you can also create your first superuser by running: caddy superuser upsert EMAIL PASS)
```

I'm clueless of what I'm doing wrong.

**Comment by bennyzen** [comment]
When I connect to the Caddy container and try to run the suggested `caddy superuser upsert` command, this happens:
```bash
/srv # caddy superuser upsert benny@example.com somepassword
Error: unknown command "superuser" for "caddy"
```

I'm using Caddy 2.9.1 with this simple Dockerfile:
```Dockerfile
FROM caddy:2.9.1-builder AS builder

RUN xcaddy build --with github.com/mohammed90/caddy-pocketbase

FROM caddy:2.9.1

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

```

**Comment by mohammed90** [comment]
> Look at this:
> 
> https POST localhost/pocketbase/superuser email_address=benny@example.com password=somepassword --verify no
> 
> I'm not able to access any `/pocketbase` route.

The API endpoints are on Caddy admin endpoint, not on your FQDN. That's what the README says:
https://github.com/mohammed90/caddy-pocketbase/blob/15c659445af3481d7b3ea48c79caeb3f55ffb899/README.md?plain=1#L37

Moreover, this format is improper because the API takes JSON, as mentioned in the README.
> email_address=benny@example.com password=somepassword



As for the commands printed in the logs, those are printed by pocketbase, and I cannot stop the log prints. Those commands aren't hooked into Caddy.


I've fixed the app customization issue and added examples.

**Comment by bennyzen** [comment]
FYI, `https POST localhost/pocketbase/superuser email_address=benny@example.com password=somepassword` translates to a POST JSON request body using [httpie CLI](https://httpie.io/docs/cli/optional-get-and-post).

BTW: it's still not working for me.

**Comment by mohammed90** [comment]
> `https POST localhost/pocketbase/superuser
> BTW: it's still not working for me.
> 
> 

Because you're still not using the admin endpoint. Please follow the instructions. Try `localhost:2019`. You'll see the magic.

**Comment by bennyzen** [comment]
Since I'm using Docker, I need to add `admin 0.0.0.0:2019` to `Caddyfile` global options and then open the 2019 port in my compose file.

Now it's working. Thank you so much for your patience.

**Comment by mohammed90** [comment]
> then open the 2019 port in my compose fil

Be careful with how you expose it and not to expose the admin endpoint to the world. Docker exposes ports to the world and overrides the firewall.

**Comment by bennyzen** [comment]
Yes, sure. After the initial creation of the superadmin, that 2019 admin port **MUST** to be closed.

**Comment by mohammed90** [comment]
If the intent is just to create the admin user, you can just copy the url from the logs, replace the IP:port with the FQDN, and navigate to the URL on the browser. You may protect it temporarily with basic auth.

You don't seem to need the custom port because it was needed based on misunderstanding. You can tell Docker to expose the admin endpoint, i.e. the 2019, to only 127.0.0.1.

**Comment by bennyzen** [comment]
Yes, you're right. Grabbing the URL from the logs is an even better approach and does not involve opening the admin port to the wild. Doing so, the setup process is much more streamlined with less steps.
